version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: local_backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run dev
      "

  frontend:
    build: ./frontend
    container_name: local_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
    command: npm run dev

volumes:
  pgdata:
